baseURL = "https://robertdiab.ca/sum"
languageCode = "en-us"
title = "Criminal Law Summaries"
subtitle = "Summaries of Substantive and Procedural Criminal law in Canada"
theme = "book"


[params]
googleAnalyticsID = "G-DZ90CS7CPE"

# (Optional, default true) Enables search function with flexsearch,
 # Index is built on fly, therefore it might slowdown your website.
 # Configuration for indexing can be adjusted in i18n folder per language.

 BookSearch = true

  Description = "Summaries of Substantive and Procedural Criminal law in Canada"
